spring:
  application:
    name: gateway
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8084

#zuul:
#  routes:
#    myproject:
#      path: /myproject/**
#      serviceId: project
    #简洁写法
#    project: /myproject/**

  # 设置全局敏感头
zuul:
  sensitive-headers:
    Cookie,Set-Cookie

  routes:
    auth:
      path: /auth/**
      serviceId: auth-server
    touda:
      path: /touda/**
      url: https://www.jianshu.com/p/
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
#security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:${server.port}/uaa/oauth/token
#      user-authorization-uri: http://localhost:${server.port}/uaa/oauth/authorize
#      client-id: zuul-gateway

