eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/

spring:
  application:
    name: auth-server
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password:
#    url: jdbc:mysql://127.0.0.1/coderiver?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  port: 8090


management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
